name: ci-daily
on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  daily-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Build & run via Python
        run: python tools/ci.py
